server:
  port: 8088
spring:
  application:
    name: massif-service
#spring.application.name使用个人用户名，防止eureka application重名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.55.254:3306/zkyq_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: ceshidb
    password: Ceshi123
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 12355
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions:
      stat-view-servlet:
        enabled: true
  rabbitmq:
    host: 192.168.55.36
    username: massif
    password: massif
eureka:
  client:
    service-url:
      defaultZone: http://192.168.55.36:8001/eureka
mybatis:
  type-aliases-package: com.ztyq.massif.model
  configuration:
    map-underscore-to-camel-case: true
logging: 
  config: classpath:log4j2.xml
