server:
  port: 8088
spring:
  application:
    name: massif-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.11:3306/etai?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: coder
    password: 7tKQQKoXQu
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 1
      validation-query-timeout: 1
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions:
      stat-view-servlet:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
mybatis:
  type-aliases-package: com.ztyq.massif.model
  configuration:
    map-underscore-to-camel-case: true
logging: 
  config: classpath:log4j2.xml